[versions]

android-gradlePlugin = "8.13.2"

# Existing versions
android-compileSdk = "34"
android-minSdk = "24"
androidx-activityCompose = "1.9.0"
androidx-core-ktx = "1.13.1"
androidx-lifecycle = "2.8.3"
compose-plugin = "1.6.11"
compose-compiler = "2.0.0"
kotlin = "2.0.0"
kotlinx-datetime = "0.6.0"
kotlinx-serialization = "1.7.3"
navigation-compose = "2.8.0-alpha10" # Jetbrains Navigation
okio = "3.9.0"

# Koin Versions
koin = "3.5.6"
koin-compose = "1.1.5"
koin-android = "3.5.6"

# Room
room = "2.7.0-alpha01"
sqlite = "2.5.0-alpha01"
ksp = "2.0.0-1.0.21"

[libraries]

# Existing libraries
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version = "2.3.11" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version = "2.3.11" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version = "2.3.11" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version = "2.3.11" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version = "2.3.11" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version = "2.3.11" }

# Koin Libraries
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }


[plugins]

androidApplication = { id = "com.android.application", version.ref = "android-gradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "android-gradlePlugin" }

kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }

composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-compiler" }
